export default {
  MANAGE_MEDICINES: 'MANAGE_MEDICINES',
  MANAGE_CARES: 'MANAGE_CARES',
  MANAGE_FOODS: 'MANAGE_FOODS',
  MANAGE_SUPPLIES: 'MANAGE_SUPPLIES',
  MANAGE_ELECTRICALS: 'MANAGE_ELECTRICALS',
  MANAGE_CARS: 'MANAGE_CARS',
  MANAGE_STAFFS: 'MANAGE_STAFFS',
  MANAGE_OLDS: 'MANAGE_OLDS',
  MANAGE_FAMILIES: 'MANAGE_FAMILIES',
  MANAGE_CARERS: 'MANAGE_CARERS'
}
